### ISSUE TITLE
Enable delete participant option for registered teams

### ISSUE THREAD

**Issue by abhikpai** [manipalutsav/frontend#159]
Create a delete participant option:

A warning/alert when the deletion of a participant leads to the following:
resultant no. of participants <  min. participants for that event

Once all members are deleted .. it should appear as unregistered event for that college .. 

The team should not appear in slotting.

Check for other dependencies/issues

**Comment by r21meghashyam** [comment]
Ensure when we are deleting, we are not going below min participants required

**Comment by Ajoy10** [comment]
In the meeting, they were discussing about the option to delete a team from an event. This is different from deleting participants from the team. Can @abhikpai confirm they need both these features?

**Comment by abhikpai** [comment]
Please add both features:

1) Delete individual participants (stop deletion after reaching min quota)
2) Delete the entire team
