### ISSUE TITLE
Text overlap in list-view of Events

### ISSUE THREAD

**Issue by abhikpai** [manipalutsav/frontend#273]
![Image](https://github.com/manipalutsav/frontend/assets/6973070/53e65b74-f07d-4d7b-af20-c235acc66007)

**Comment by abhikpai** [comment]
Why was list view introduced? Is it necessary? 

If it is included, it must be clickable just like tile view

**Comment by r21meghashyam** [comment]
Was not important, but to have a simplified view of all events
