### ISSUE TITLE
Update validation in Registration Page to include Registration ID with Prefix "MAGE"

### ISSUE THREAD

**Issue by abhikpai** [manipalutsav/frontend#290]
![Image](https://github.com/manipalutsav/frontend/assets/6973070/f06b6e68-f249-4fd2-8e0f-455d27ca41c6)

Currently this error is coming for MAGE employees during registration. 

Kindly allow Registration No, with "MAGE" prefix as a valid entry.

**Comment by Ajoy10** [comment]
Closing as MAGE followed by 8 digits is already a valid input in the system
